In [86]:
class meraLR:
    def __init__(self):
        self.m = None
        self.b =None
    
    def fit(self,X_train,Y_train):
        neumerator = 0
        denominator = 0
        for i in range(X_train.shape[0]):
            neumerator=neumerator+((X_train[i]-X_train.mean())*(Y_train[i]-Y_train.mean()))
            denominator=denominator+((X_train[i]-X_train.mean())*(X_train[i]-X_train.mean()))
        self.m=neumerator/denominator
        self.b = Y_train.mean()-(self.m*X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):
        print(X_test)
        return self.m*X_test +self.b

In [87]:
import numpy as np
import pandas as pd

In [88]:
df = pd.read_csv("package.csv")
df.head()

,CGPA,Placement
0,3.70,4.74
1,3.90,7.20
2,3.50,3.40
3,3.10,2.40
4,3.89,7.88


In [89]:
X=df.iloc[:,0].values # all row and 0th column
Y=df.iloc[:,1].values # all row and 1th column

In [90]:
X

array([3.7 , 3.9 , 3.5 , 3.1 , 3.89, 2.99, 2.5 , 3.73, 3.43])

In [91]:
Y

array([4.74, 7.2 , 3.4 , 2.4 , 7.88, 2.01, 1.78, 5.01, 3.2 ])

In [92]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [93]:
X_train.shape

(7,)

In [94]:
lr = meraLR()

In [95]:
lr.fit(X_train,Y_train)

2.6408765870506397
-5.438302524687454


In [96]:
X_test

array([3.89, 3.9 ])

In [97]:
Y_test

array([7.88, 7.2 ])

In [98]:
print(lr.predict(X_test[1]))

3.9
4.861116164810041
